#! /usr/bin/env ruby

require 'pg'

db = PG.connect(dbname: 'expenses')

argument = ARGV.first

def print_list(db)
  result = db.exec "SELECT * FROM expenses;"

  result.each do |tuple|
    columns = [ tuple['id'].rjust(3),
                tuple['created_on'].rjust(10),
                tuple['amount'].rjust(12),
                tuple['memo'] ]

    puts columns.join ' | '
  end
end

def print_help
  puts <<HELP
An expense recording system

Commands:

add AMOUNT MEMO [DATE] - record a new expense
clear - delete all expenses
list - list all expenses
delete NUMBER - remove expense with id NUMBER
search QUERY - list expenses with a matching memo field
HELP
end

print_list(db) if argument == 'list'
print_help if argument == 'help'
