#! /usr/bin/env ruby

require 'pg'
require 'pry'

db = PG.connect(dbname: 'expenses')

arguments = ARGV

def message(text)
  puts text
end

def valid_arguments?(arguments)
  if arguments[0] == 'add'&& (arguments[1].nil? || arguments[2].nil?)
    false
  else
    true
  end
end

command = arguments[0]
amount = arguments[1]
memo = arguments[2]

def print_list(db)
  result = db.exec "SELECT * FROM expenses;"

  result.each do |tuple|
    columns = [ tuple['id'].rjust(3),
                tuple['created_on'].rjust(10),
                tuple['amount'].rjust(12),
                tuple['memo'] ]

    puts columns.join ' | '
  end
end

def print_help
  puts <<~HELP
    An expense recording system

    Commands:
    
    add AMOUNT MEMO [DATE] - record a new expense
    clear - delete all expenses
    list - list all expenses
    delete NUMBER - remove expense with id NUMBER
    search QUERY - list expenses with a matching memo field
  HELP
end

def add_expense(db, amount, memo)
  db.exec("INSERT INTO expenses (amount, memo) VALUES (#{amount.to_f}, '#{memo}')")
end

if command == 'list' 
  print_list(db) 
elsif command == 'help'
  print_help
elsif command == 'add'
  if valid_arguments? arguments
    add_expense(db, amount, memo)
  else
    message 'You must provide an amount and memo.'
  end
end
